version: '3.8'
services:
  db:
    image: mysql:8.0
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "49497:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - management-network

  management:
    build:
      context: ..
      dockerfile: .devcontainer/docker/Dockerfile
    container_name: management
    ports:
      - "8081:8080"
    volumes:
      - ../:/management
    command: sleep infinity
    networks:
      - management-network
    tty: true
    depends_on:
      - db

volumes:
  mysql-data:

networks:
  management-network:
    external: false
