version: '3.8'

services:
  angular:
    build:
      context: ..
      dockerfile: .devcontainer/docker/Dockerfile
    container_name: angular
    volumes:
      - ../:/angular
      - /angular/pain-log/node_module
    ports:
      - "4200:4200"
    tty: true
    working_dir: /angular/pain-log
